# Generated by Django 4.0.6 on 2022-07-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('registrationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=46, unique=True)),
                ('area', models.IntegerField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('registrationDate', models.DateTimeField()),
                ('propertyType', models.CharField(choices=[('APT', 'Apartments'), ('HTL', 'Hotel'), ('HSE', 'House'), ('NNN', 'Unknown')], default='NNN', max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inWhite.user')),
            ],
        ),
    ]
