# Generated by Django 4.0.6 on 2022-07-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0006_owner_alter_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user_id',
            new_name='user',
        ),
    ]
