# Generated by Django 4.0.6 on 2022-07-14 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inWhite', '0007_rename_user_id_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fName',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lName',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
