# Generated by Django 4.0.6 on 2022-07-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0008_alter_owner_fname_alter_owner_lname_alter_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='propertyType',
            new_name='property_type',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lName',
        ),
    ]
