# Generated by Django 4.0.6 on 2022-07-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0009_rename_propertytype_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APT', 'Apartments'), ('HTL', 'Hotel'), ('HSE', 'House'), ('NNN', 'Unknown')], default='NNN', max_length=15),
        ),
    ]
