# Generated by Django 4.0.6 on 2022-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0010_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APT', 'Apartments'), ('HTL', 'Hotel'), ('HSE', 'House'), ('NNN', 'Unknown')], default='NNN', max_length=3),
        ),
    ]
