# Generated by Django 4.0.6 on 2022-07-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0011_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
    ]
