# Generated by Django 4.0.6 on 2022-07-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0013_rename_name_property_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
    ]
