# Generated by Django 4.0.6 on 2022-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0014_rename_title_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
