# Generated by Django 4.0.6 on 2022-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0017_alter_property_owner_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('NNN', 'Unknown'), ('APT', 'Apartments'), ('HTL', 'Hotel'), ('HSE', 'House')], default='NNN', max_length=3),
        ),
    ]
