# Generated by Django 4.0.6 on 2022-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0018_alter_property_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='registrationDate',
            new_name='registration_date',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('NNN', '-----'), ('APT', 'Apartments'), ('HTL', 'Hotel'), ('HSE', 'House')], default='NNN', max_length=3),
        ),
    ]
