# Generated by Django 4.0.6 on 2022-07-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0019_rename_registrationdate_property_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
    ]
