# Generated by Django 4.0.6 on 2022-07-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inWhite', '0021_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
